import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { Search, Filter, Download, ArrowLeft, ArrowRight, RefreshCw, ClipboardList } from 'lucide-react';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export default function LeaveHistory({ user, showToast }) {
  const [leaves, setLeaves] = useState([]);
  const [loading, setLoading] = useState(false);
  
  // Filter States
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [leaveType, setLeaveType] = useState("");
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const limit = 10;

  const fetchLeaves = async () => {
    setLoading(true);
    try {
      const filters = {
        page,
        limit,
        search,
        status,
        leave_type: leaveType
      };
      
      const res = await api.leaves.getAll(filters);
      setLeaves(res.data || []);
      setTotalPages(res.pages || 1);
    } catch (err) {
      showToast(err.message || "Failed to load leave records history.", "error");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLeaves();
  }, [page, status, leaveType]);

  const handleSearchSubmit = (e) => {
    e.preventDefault();
    setPage(1);
    fetchLeaves();
  };

  // Modern Client-Side PDF Generation using jsPDF and jspdf-autotable
  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF({ orientation: "landscape" });

      // Title & Branding Header
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(141, 43, 43); // #8d2b2b
      doc.text("ALARD PURODHIA COLLEGE OF ENGINEERING & RESEARCH (APCOER)", 14, 18);
      
      doc.setFontSize(12);
      doc.setTextColor(80, 80, 80);
      doc.text("Faculty Leave Registry System Report Summary", 14, 25);
      
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(9);
      doc.text(`Generated At: ${new Date().toLocaleString()}`, 14, 31);
      doc.text(`Generated By: ${user.name} (${user.role})`, 14, 36);

      // Construct table data columns
      const headers = [["Leave ID", "Faculty Name", "Department", "Leave Type", "Start Date", "End Date", "Status", "Approver Remarks"]];
      
      const rows = leaves.map(leave => [
        leave.leave_id,
        leave.Faculty?.name || "N/A",
        leave.Faculty?.department || "N/A",
        leave.leave_type,
        leave.from_date,
        leave.to_date,
        leave.status.toUpperCase(),
        leave.remarks || "-"
      ]);

      // Call autoTable plugin
      doc.autoTable({
        startY: 42,
        head: headers,
        body: rows,
        headStyles: { fillColor: [141, 43, 43], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [250, 245, 245] },
        margin: { left: 14, right: 14 },
        styles: { fontSize: 9, cellPadding: 4 },
        theme: "striped"
      });

      doc.save(`apcoer_leave_registry_report_${Date.now()}.pdf`);
      showToast("Premium leave summary PDF generated and downloaded successfully.", "success");
    } catch (err) {
      console.error(err);
      showToast("Failed to compile and download PDF report file.", "error");
    }
  };

  return (
    <div className="history-page-wrapper">
      <div className="page-header header-with-actions">
        <div>
          <h1 className="page-title">Leave Registry & Reports</h1>
          <p className="page-subtitle">Search, filter, analyze leave records, and download official PDF summaries.</p>
        </div>
        <button className="btn btn-primary" onClick={handleDownloadPDF} disabled={leaves.length === 0}>
          <Download size={18} />
          <span>Export PDF Report</span>
        </button>
      </div>

      {/* Filter panel card */}
      <div className="glass-card filters-card">
        <form onSubmit={handleSearchSubmit} className="filters-form">
          <div className="filter-group search-box">
            <label htmlFor="searchInput">Search Faculty Name / Email / Department</label>
            <div className="search-input-wrapper">
              <Search size={16} className="search-icon" />
              <input
                id="searchInput"
                type="text"
                className="form-control"
                placeholder="E.g., Dr. Nilesh..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
          </div>

          <div className="filter-group">
            <label htmlFor="statusSelect">Approval Status</label>
            <select
              id="statusSelect"
              className="form-control"
              value={status}
              onChange={(e) => { setStatus(e.target.value); setPage(1); }}
            >
              <option value="">All Statuses</option>
              <option value="PENDING">Pending Action</option>
              <option value="APPROVED">Approved Requests</option>
              <option value="REJECTED">Rejected Requests</option>
            </select>
          </div>

          <div className="filter-group">
            <label htmlFor="typeSelect">Leave Category</label>
            <select
              id="typeSelect"
              className="form-control"
              value={leaveType}
              onChange={(e) => { setLeaveType(e.target.value); setPage(1); }}
            >
              <option value="">All Categories</option>
              <option value="Casual Leave">Casual Leave</option>
              <option value="Medical Leave">Medical Leave</option>
              <option value="Earned Leave">Earned Leave</option>
              <option value="Movement Leave">Movement Leave</option>
            </select>
          </div>

          <div className="filter-actions-btn-row">
            <button type="submit" className="btn btn-secondary filter-search-btn">
              Apply Filter
            </button>
            <button 
              type="button" 
              className="btn btn-secondary refresh-btn"
              onClick={() => { setSearch(""); setStatus(""); setLeaveType(""); setPage(1); fetchLeaves(); }}
            >
              <RefreshCw size={16} />
            </button>
          </div>
        </form>
      </div>

      {/* Data Card list */}
      <div className="glass-card table-card">
        {loading ? (
          <div className="table-loader">
            <RefreshCw size={32} className="spin-icon" />
            <p>Loading synchronized SQL records...</p>
          </div>
        ) : leaves.length === 0 ? (
          <div className="empty-table-placeholder">
            <ClipboardList size={48} className="empty-icon" />
            <h3>No Leave Registry Matches</h3>
            <p>Try modifying your dynamic filter search strings or check seed accounts.</p>
          </div>
        ) : (
          <>
            <div className="table-responsive">
              <table className="premium-table">
                <thead>
                  <tr>
                    <th>Leave ID</th>
                    <th>Faculty Name</th>
                    <th>Department</th>
                    <th>Category</th>
                    <th>Dates</th>
                    <th>Status</th>
                    <th>Remarks</th>
                  </tr>
                </thead>
                <tbody>
                  {leaves.map((l) => (
                    <tr key={l.leave_id}>
                      <td><code className="text-code">{l.leave_id.substr(0, 10)}...</code></td>
                      <td><strong>{l.Faculty?.name || "Dr. Nilesh Bhosale"}</strong></td>
                      <td>{l.Faculty?.department || "Computer Engineering"}</td>
                      <td><span className="type-badge">{l.leave_type}</span></td>
                      <td>{l.from_date} to {l.to_date}</td>
                      <td>
                        <span className={`badge badge-${l.status.toLowerCase()}`}>
                          {l.status}
                        </span>
                      </td>
                      <td><span className="table-remarks-text">{l.remarks || "-"}</span></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Pagination Controls */}
            <div className="pagination-wrapper">
              <span className="pagination-info">
                Page <strong>{page}</strong> of <strong>{totalPages}</strong>
              </span>
              <div className="pagination-buttons">
                <button 
                  className="btn btn-secondary btn-icon"
                  disabled={page <= 1}
                  onClick={() => setPage(p => p - 1)}
                >
                  <ArrowLeft size={16} />
                </button>
                <button 
                  className="btn btn-secondary btn-icon"
                  disabled={page >= totalPages}
                  onClick={() => setPage(p => p + 1)}
                >
                  <ArrowRight size={16} />
                </button>
              </div>
            </div>
          </>
        )}
      </div>

      <style>{`
        .header-with-actions {
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 20px;
        }

        .filters-form {
          display: grid;
          grid-template-columns: 2fr 1fr 1fr auto;
          gap: 16px;
          align-items: flex-end;
        }

        .search-input-wrapper {
          position: relative;
        }

        .search-icon {
          position: absolute;
          left: 12px;
          top: 50%;
          transform: translateY(-50%);
          color: var(--text-secondary);
        }

        .search-input-wrapper .form-control {
          padding-left: 36px;
        }

        .filter-actions-btn-row {
          display: flex;
          gap: 8px;
        }

        .refresh-btn {
          padding: 12px;
        }

        .spin-icon {
          animation: spin 1s linear infinite;
        }

        .table-loader {
          text-align: center;
          padding: 60px 0;
          color: var(--text-secondary);
        }

        .table-loader p {
          margin-top: 12px;
          font-weight: 600;
        }

        .empty-table-placeholder {
          text-align: center;
          padding: 80px 0;
          color: var(--text-secondary);
        }

        .empty-icon {
          color: var(--border-glass);
          margin-bottom: 16px;
        }

        .empty-table-placeholder h3 {
          font-size: 1.2rem;
          font-weight: 700;
          color: var(--text-primary);
          margin-bottom: 4px;
        }

        .text-code {
          background-color: rgba(0, 0, 0, 0.04);
          padding: 3px 6px;
          border-radius: 4px;
          font-size: 0.82rem;
          color: var(--brand-dark);
        }

        .type-badge {
          font-weight: 600;
          color: var(--text-secondary);
        }

        .table-remarks-text {
          max-width: 180px;
          display: inline-block;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
          font-size: 0.88rem;
          color: var(--text-secondary);
        }

        .pagination-wrapper {
          display: flex;
          justify-content: space-between;
          align-items: center;
          border-top: 1px solid var(--border-glass);
          padding-top: 20px;
          margin-top: 20px;
        }

        .pagination-info {
          font-size: 0.9rem;
          color: var(--text-secondary);
        }

        .pagination-buttons {
          display: flex;
          gap: 8px;
        }

        .btn-icon {
          padding: 10px;
        }

        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }

        @media (max-width: 991px) {
          .header-with-actions {
            flex-direction: column;
            align-items: flex-start;
          }
          .filters-form {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </div>
  );
}
